
// Resume Mock Data - All content centralized here for easy updates

export const personalInfo = {
    name: "Afzal Habib",
    title: "Lead Full Stack Engineer & System Architect",
    phone: "+92 323 1103430",
    email: "afzalhaabib786@gmail.com",
    location: "Harbanspura, Lahore, Pakistan",
    linkedin: "www.linkedin.com/in/afzalhabibdev",
    github: "https://github.com/AfzalHabibi",
    portfolio: "https://afzalhabib.com/",
    profileImage: "resume/images/profile-picture-professional-2.png",
}

export const summary = `Lead Full-Stack Engineer & System Architect with 6+ years of experience designing and delivering scalable web and mobile systems. Specialized in Next.js, NestJS, Python, FastAPI, and MERN/PERN stacks with strong expertise in building enterprise-grade ERP/CRM platforms, e-commerce systems, real-time applications, and AI-powered integrations. Focused on system architecture, software Engineering practices, and translating complex business requirements into reliable, scalable software solutions.`

export const experiences = [
    {
        title: "Lead Full Stack Developer",
        company: "Spell Link Pvt Ltd",
        location: "New York, USA",
        duration: "Feb 2025 - Present",
        highlights: [
            "Leading and shipping TravelTourUp — travel booking for flights, hotels, and rental cars (Next.js, Supabase, Duffel, CarTrawler)",
            "Leading CarHub — Car Rental & Sale marketplace where sellers list vehicles for sale or rent and customers book securely",
            "Leading estimation-company CRM in Laravel with full sales workflow, client portal, and integrated chat",
        ],
        borderColor: "border-slate-900",
    },
    {
        title: "Senior Full Stack Developer",
        company: "Digi Era Pro",
        location: "New York, USA",
        duration: "Sep 2024 - Feb 2025",
        highlights: [
            "Lead development of enterprise ERP/CRM system with 13+ integrated modules",
            "Implemented real-time communication(whatsapp and slack inspired) using Supabase WebSockets",
            "Managed 9-stage workflow from lead generation to project completion",
        ],
        borderColor: "border-slate-900",
    },
    {
        title: "Full Stack Developer",
        company: "Devgiant",
        location: "Lahore",
        duration: "Fab 2023 - Sep 2024",
        highlights: [
            "Developed e-commerce and real estate platforms",
            "Built inventory systems with real-time tracking",
            "Created secure APIs with Node.js/Express.js",
        ],
   
        borderColor: "border-slate-700",
    },
    {
        title: "Frontend Developer",
        company: "Heapware Technologies",
        location: "Lahore",
        duration: "Jan 2022 - Jan 2023",
        highlights: [
            "Built React web apps and real estate sites with modern UI",
        ],
   
        borderColor: "border-slate-700",
    },
    {
        title: "MERN Stack Developer",
        company: "Corelogix",
        location: "Gulberg, Lahore",
        duration: "Fab 2020 - Dec 2021",
        highlights: [
            "Built frontend projects and learned modern dev practices",
        ],
   
        borderColor: "border-slate-500",
    },
]

export const education = [
    {
        degree: "BS Software Engineering",
        institution: "University of Engineering and Technology, Lahore",
        duration: "2019 - 2023",
    },
    {
        degree: "FSc Pre-Engineering",
        institution: "Faizaia Inter College",
        duration: "2017 - 2019",
    },
]

export const certifications = [
    {
        name: "MERN Stack Development",
        issuer: "House of Professional",
        date: "Mar 2019",
        location: "Johar Town, Lahore",
    },
    {
        name: "MERN Stack Development",
        issuer: "Ideoversity",
        date: "Apr 2020",
        location: "Arfa IT Tower, Lahore",
    },
    {
        name: 'AI Automation & Workflow Engineering',
        issuer: 'Udemy',
        date: 'Nov 2023',
        location: 'Online',
      },
]

export const languages = [
    { name: "English", level: "Professional" },
    { name: "Urdu", level: "Native" },
    { name: "Punjabi", level: "Native" },
]

export const coreCompetencies = [
    "Full Stack Development",
    "MERN Stack Development",
    // "PERN Stack Development",
    "Python Development",
    "AI Integration",
    "System Architecture",
    // "API Design",
    "Database Design",
    "Real-time Applications",
    "Mobile Development",
    "Payment Integration",
    // "Authentication Systems",
]

export const tools = ["Git", "GitLab","Docker","CI/CD Pipeline", "Figma", "Vercel","Github Copilot","Cursor","OpenAI API"]

export const skills = {
    frontend: {
        icon: "Layers",
        title: "Frontend Development",
        items: [
            {
                name: "Languages & Core",
                technologies: "HTML5, CSS3, JavaScript (ES6+), TypeScript",
                level: "Expert",
                experience: "6 years experience",
                borderColor: "border-slate-900",
            },
            {
                name: "Frameworks & Libraries",
                technologies: "React.js, Next.js, Redux Toolkit, Context API",
                level: "Expert",
                experience: "5 years experience",
                borderColor: "border-slate-900",
            },
            {
                name: "Styling Frameworks",
                technologies: "Tailwind CSS, Bootstrap, ShadCN UI, Radix UI, Styled Components",
                level: "Expert",
                experience: "6 years experience",
                borderColor: "border-slate-900",
            },
            {
                name: "Animation & Motion",
                technologies: "Framer Motion, GSAP, Lenis, CSS Animations",
                level: "Advanced",
                experience: "4 years experience",
                borderColor: "border-slate-900",
            },
            {
                name: "State Management",
                technologies: "Redux, Redux Toolkit, Context API",
                level: "Advanced",
                experience: "4 years experience",
                borderColor: "border-slate-900",
            },
        ],
    },
    backend: {
        icon: "Server",
        title: "Backend Development",
        items: [
            {
                name: "Runtime & Frameworks",
                technologies: "Node.js, Express.js, Nest.js, Python, FastAPI, Core PHP, REST APIs",
                level: "Advanced",
                experience: "6 years experience",
                borderColor: "border-slate-900",
            },
            {
                name: "Python & FastAPI",
                technologies: "Python, FastAPI, Pydantic, Async APIs, Background Tasks",
                level: "Advanced",
                experience: "2 years experience",
                borderColor: "border-slate-700",
            },
            {
                name: "Authentication & Security",
                technologies: "JWT, NextAuth.js, OAuth2, SHA-1 , bcrypt, 2FA",
                level: "Advanced",
                experience: "5 years experience",
                borderColor: "border-slate-700",
            },
            {
                name: "Real-time Communication",
                technologies: "Socket.io, WebSockets, Supabase Realtime",
                level: "Advanced",
                experience: "4 years experience",
                borderColor: "border-slate-700",
            },
            {
                name: "API Development",
                technologies: "RESTful APIs, Middleware, Validation , Error Handling",
                level: "Advanced",
                experience: "5 years experience",
                borderColor: "border-slate-700",
            },
        ],
    },
    database: {
        icon: "Database",
        title: "Database & Storage",
        items: [
            {
                name: "NoSQL Databases",
                technologies: "MongoDB, MongoDB Atlas, Aggregation Pipelines",
                level: "Advanced",
                experience: "5 years experience",
                borderColor: "border-slate-700",
            },
            {
                name: "SQL Databases",
                technologies: "MySQL, PostgreSQL, Complex Queries, Optimization",
                level: "Advanced",
                experience: "5 years experience",
                borderColor: "border-slate-900",
            },
            {
                name: "ORM & BaaS",
                technologies: "Prisma ORM, Supabase, Mongoose ODM",
                level: "Advanced",
                experience: "4 years experience",
                borderColor: "border-slate-700",
            },
        ],
    },
    mobile: {
        icon: "Smartphone",
        title: "Mobile Development",
        items: [
            {
                name: "Cross-Platform Framework",
                technologies: "React Native, Expo, EAS Build, OTA Updates",
                level: "Advanced",
                experience: "4 years experience",
                borderColor: "border-slate-700",
            },
            {
                name: "Navigation & Storage",
                technologies: "React Navigation, Redux",
                level: "Advanced",
                experience: "4 years experience",
                borderColor: "border-slate-700",
            },
            {
                name: "Native Features",
                technologies: "Camera, Push Notifications, Deep Linking",
                level: "Advanced",
                experience: "4 years experience",
                borderColor: "border-slate-700",
            },
        ],
    },
    integrations: {
        icon: "Settings",
        title: "Third-Party Integrations",
        items: [
            {
                name: "AI Integration",
                technologies: "OpenAI API, LLM Integration, AI Assistants",
                level: "Advanced",
                experience: "2 years experience",
                borderColor: "border-slate-900",
            },
            {
                name: "Payment Gateways",
                technologies: "Squareup,Stripe, Webhooks, ",
                level: "Advanced",
                experience: "5 years experience",
                borderColor: "border-slate-700",
            },
            {
                name: "Cloud Services",
                technologies: "AWS S3, CDN, Google APIs, SendGrid, AWS SES",
                level: "Advanced",
                experience: "5 years experience",
                borderColor: "border-slate-700",
            },
            {
                name: "Shipping & Email",
                technologies: "Shippo,SendGrid, AWS SES , Email Templates, Automation",
                level: "Advanced",
                experience: "5 years experience",
                borderColor: "border-slate-700",
            },
        ],
    },
    // ai: {
    //     icon: "Settings",
    //     title: "AI & Machine Learning",
    //     items: [
    //         {
    //             name: "AI Integration",
    //             technologies: "OpenAI API, LLM Integration, Prompt Engineering, RAG, AI Assistants",
    //             level: "Advanced",
    //             experience: "2 years experience",
    //             borderColor: "border-slate-900",
    //         },
    //         // {
    //         //     name: "AI-Assisted Development",
    //         //     technologies: "GitHub Copilot, Cursor, Code Generation, Workflow Automation",
    //         //     level: "Advanced",
    //         //     experience: "2 years experience",
    //         //     borderColor: "border-slate-700",
    //         // },
    //     ],
    // },
    devops: {
        icon: "GitBranch",
        title: "DevOps & Tools",
        items: [
            {
                name: "Version Control",
                technologies: "Git, GitHub, GitLab, Branching Strategies",
                level: "Expert",
                experience: "6 years experience",
                borderColor: "border-slate-900",
            },
            {
                name: "Deployment & CI/CD",
                technologies: "Docker, Vercel, Digital Ocean, GitHub Actions",
                level: "Advanced",
                experience: "5 years experience",
                borderColor: "border-slate-900",
            },
            {
                name: "Design & Documentation",
                technologies: "Figma, Postman, Technical Writing , Prompt Engineering",
                level: "Advanced",
                experience: "6 years experience",
                borderColor: "border-slate-900",
            },
        ],
    },
}

/** Featured work at Spell Link Pvt Ltd — shown on a dedicated resume page before the general project list */
export const spellLinkProjects = [
    {
        title: "TravelTourUp",
        subtitle: "Travel Booking Platform (Flights, Hotels & Cars)",
        role: "Founder & Lead Full Stack Developer",
        company: "Spell Link Pvt Ltd",
        duration: "Oct 2025 - Present",
        description:
            "Full-featured travel booking platform where users book flights, hotels, and rental cars from one interface. API-driven architecture focused on performance, reliability, and a smooth end-to-end experience from search to confirmation.",
        technologies: [
            "Next.js",
            "Supabase (Auth & Database)",
            "Resend",
            "Duffel (Flights & Hotels)",
            "CarTrawler (Car Rentals)",
        ],
        highlights: [
            "Designed overall system architecture and led delivery from planning through production deployment",
            "Integrated third-party travel APIs for flights, hotels, and car rentals with resilient error handling",
            "Built frontend and backend features end-to-end, including auth, booking flows, and transactional email",
            "Implemented Supabase-backed authentication, persistence, and secure access patterns across booking journeys",
            "Configured Resend for transactional emails (confirmations, updates) with reliable templating and delivery",
            "Tuned search-to-checkout UX and API usage for responsive results pages and fewer abandoned sessions",
            "Established a consistent API integration layer with retries, timeouts, and structured logging for Duffel and CarTrawler",
            "Normalized itinerary, passenger, and rental-driver data across suppliers before persisting confirmed bookings",
            "Shipped mobile-first, responsive UI with clear itinerary review, pricing breakdowns, and accessible form patterns",
            "Applied environment-based configuration, least-privilege credentials, and strict separation of test vs production keys",
        ],
        borderColor: "border-slate-900",
        isLarge: true,
        liveUrl: "https://www.traveltourup.com",
    },
    {
        title: "CarHub",
        subtitle: "Car Sale & Rental Marketplace",
        role: "Lead Full Stack Developer",
        company: "Spell Link Pvt Ltd",
        duration: "Aug 2025 - Nov 2025",
        description:
            "Car Rental & Sale marketplace where registered users create accounts, list vehicles for sale or rent, and buyers or renters discover listings and complete bookings. Emphasis on trust, clear listing workflows, and a straightforward customer journey.",
        technologies: ["Next.js", "NestJS", "PostgreSQL", "TypeScript", "JavaScript", "REST APIs", "Tailwind CSS"],
        highlights: [
            "Implemented account onboarding, profiles, and role-aware access for sellers and customers",
            "Built listing management for sale and rental inventory with media, pricing, and availability",
            "Developed booking and enquiry flows so customers can reserve or request vehicles from active listings",
            "Shipped admin and moderation tools to keep listings quality high and disputes low",
            "Delivered discovery with search, filters, and sorting so buyers can narrow by price, location, and vehicle type",
            "Hardened forms, validation, and Next.js security defaults (CSRF, policies, guarded routes) across the marketplace",
            "Designed PostgreSQL schema and indexes for high-traffic marketplace queries (geo, price bands, make/model, availability)",
            "Built seller dashboards for listing performance, enquiries, and booking funnel visibility",
            "Implemented validated media uploads, organized storage, and thumbnail generation for multi-photo vehicle galleries",
            "Added email notifications for new enquiries, booking status changes, and listing approvals or rejections",
        ],
        borderColor: "border-slate-900",
        isLarge: true,
        liveUrl: "https://carhub.pk",
    },
    {
        title: "Estimation Company CRM",
        subtitle: "CRM with Client Portal & Chat",
        role: "Lead Full Stack Developer",
        company: "Spell Link Pvt Ltd",
        duration: "Feb 2025 - Jul 2025",
        description:
            "End-to-end Laravel CRM tailored for an estimation business: leads, quotes, jobs, documents, and reporting, plus a dedicated client portal and real-time chat so staff and clients stay aligned without email overload.",
        technologies: ["Laravel", "PHP", "MySQL", "WebSockets / Realtime", "Blade", "JavaScript"],
        highlights: [
            "Modeled CRM entities and permissions for estimators, managers, and client-facing users",
            "Delivered client portal for estimates, approvals, file exchange, and status visibility",
            "Integrated in-app chat for fast clarification between teams and clients on active jobs",
            "Built dashboards and exports for pipeline visibility and operational reporting",
            "Implemented lead-to-quote-to-job workflows with stage tracking, assignments, and audit-friendly history",
            "Centralized documents and revision context so estimates, drawings, and approvals stay attached to the right job",
            "Shipped quote versioning with readable change history so everyone aligns on scope, line items, and totals",
            "Added tasks, due dates, and clear ownership handoffs between estimators and coordinators on active opportunities",
            "Implemented role-scoped notifications for portal replies, approvals, and escalations so nothing sits unread in email",
            "Used soft deletes, immutable activity timelines, and consistent audit fields for handovers and dispute review",
        ],
        borderColor: "border-slate-700",
        isLarge: true,
        liveUrl: "",
    },
]

export const projects = [
    {
        title: "Depllc ERP/CRM System",
        role: "Lead Full-Stack Developer & System Architect",
        duration: "Sep 2024 - Jan 2025",
        description:
            "Enterprise-grade ERP/CRM with 13+ modules including lead management, project tracking, real-time communication, and role-based permissions for complex business workflows.",
        technologies: ["Next.js", "TypeScript", "MongoDB", "Supabase", "Redux Toolkit", "AWS S3", "Socket.io", "Python", "FastAPI", "OpenAI API"],
        highlights: [
            'Architected complete system with 13+ interconnected modules',
            'Implemented multi-tier authentication with 2FA for admin and employees',
            'Built dynamic role management system with hierarchical permissions',
            'Developed 9-stage workflow process from lead to project completion',
            'Integrated Supabase for real-time communication and notifications',
            'Implemented secure file storage with AWS S3 and document version control',
            'Designed client portal for project visibility and communication',
            'Integrated Python/FastAPI microservices and OpenAI API for AI-assisted workflows',
        ],
        borderColor: "border-slate-900",
        isLarge: true,
        liveUrl: "",
    },
    {
        title: "E-Commerce Platform (MERN Stack)",
        role: "Full-Stack Developer",
        duration: "Jun 2024 - Aug 2024",
        description:
            "Full-featured e-commerce solution with product catalog, shopping cart, secure checkout, and admin dashboard for inventory management.",
        technologies: ["React", "Node.js", "Express.js", "MongoDB", "Squareup", "Shippo", "Redux"],
        highlights: [
            'Developed complete user authentication system with JWT',
            'Built responsive product listing with search and filtering',
            'Implemented shopping cart with session persistence',
            'Integrated Squareup payment gateway for secure transactions',
            'Created admin dashboard for product and order management',
            'Built order history and tracking system',
        ],
        borderColor: "border-slate-900",
        isLarge: true,
        liveUrl: "https://pg-shop.cognitivebeam.com/",
    },
    {
        title: "Inventory Management System",
        role: "Full-Stack Developer",
        duration: "Feb 2024 - Jun 2024",
        description:
            "Comprehensive inventory tracking with supplier management, automated alerts, and role-based access control.",
        technologies: ["MERN", "MySQL", "Prisma ORM", "Bootstrap", "Socket.io", "JWT"],
        highlights: [
            'Designed and implemented complete database schema',
            'Built inventory tracking system with real-time updates',
            'Developed automated low-stock alert system',
            'Implemented comprehensive reporting with export functionality',
            'Built role-based access control for different user levels',
            'Created audit logging for inventory transactions',
        ],
        borderColor: "border-slate-900",
        isLarge: false,
        liveUrl: "",
    },
    {
        title: "Point of Sale (POS) System",
        role: "Full-Stack Developer",
        duration: "Jan 2024",
        description:
            "Professional POS for retail with fast checkout, barcode support, invoice generation, and sales analytics.",
        technologies: ["Core PHP", "MySQL", "JavaScript", "Bootstrap", "TCPDF"],
        highlights: [
            'Developed fast and responsive sales processing interface',
            'Implemented product management with product recipies',
            'Built automated invoice generation with PDF export',
            'Implemented sales analytics and reporting dashboard',
        ],
        borderColor: "border-slate-900",
        isLarge: false,
        liveUrl: "",
    },
    {
        title: "E-Commerce Mobile App",
        role: "Mobile Developer",
        duration: "Sep 2023 - Dec 2023",
        description: "Cross-platform shopping app with product catalog, cart, and secure payment processing.",
        technologies: ["React Native", "Expo", "Redux"],
        highlights: [
            'Developed cross-platform app for iOS and Android',
            'Implemented smooth navigation with React Navigation',
            'Built product catalog with infinite scroll',
            'Created shopping cart with persistent storage',
            'Integrated secure payment processing',
            'Implemented push notifications for order updates',
            'Optimized performance for smooth user experience',
            'Built user profile and order history features',
            'Developed search and filtering functionality',
            'Created wishlist and favorites feature',
        ],
        borderColor: "border-slate-700",
        isLarge: false,
        liveUrl: "",
    },
    {
        title: "Inventory Mobile App",
        role: "Mobile Developer",
        duration: "May - Aug 2023",
        description: "Mobile inventory management with barcode scanning and offline-first architecture.",
        technologies: ["React Native", "Expo", "Redux"],
        highlights: [
            'Developed cross-platform mobile app with React Native',
            'Implemented barcode scanning with Expo Camera',
            'Built offline-first architecture with SQLite',
            'Created real-time stock tracking system',
            'Developed supplier management module',
            'Implemented automated low-stock alerts',
            'Built comprehensive reporting with export functionality',
            'Created data synchronization mechanism',
            'Implemented user authentication and role-based access control',
            'Built user profile and order history features',
        ],
        borderColor: "border-slate-500",
        isLarge: false,
        liveUrl: "",
    },
    {
        title: "Real Estate Website",
        role: "Frontend Developer",
        duration: "2023",
        description:
            "Modern property showcase with advanced filtering, image galleries, Google Maps integration, and SEO optimization.",
        technologies: ["HTML5", "CSS3", "JavaScript", "Bootstrap", "Figma"],
        highlights: [
            'Designed and developed fully responsive layout',
            'Implemented advanced property filtering system',
            'Created interactive image galleries with lightbox',
            'Integrated Google Maps for property locations',
            'Built contact forms with validation',
            'Optimized images and performance for fast loading',
            'Implemented SEO best practices',
            'Collaborated with designers using Figma',

        ],
        borderColor: "border-slate-500",
        isLarge: false,
        liveUrl: "",
    },
    {
        title: "CE Prop Real Estate Website",
        role: "Frontend Developer & Backend Integration",
        duration: "2022",
        description: "Comprehensive real estate platform with property listings, agent management, and enquiry forms",
        technologies: ["Bootstrap", "EJS", "JavaScript", "CSS3", "HTML5", "Font Awesome", "Node.js", "Express.js"],
        highlights: [
            'Developed complete frontend using Bootstrap from scratch',
            'Implemented responsive navigation with dropdown menus',
            'Created dynamic property grid pages with filtering',
            'Built agent listing and profile pages',
            'Integrated enquiry forms for property sales/rentals',
            'Ensured cross-browser compatibility and mobile responsiveness',
        ],
        borderColor: "border-slate-500",
        isLarge: false,
        liveUrl: "https://www.ceprop.co.za",
    },
    {
        title: "Pentz Properties Real Estate Website",
        role: "Frontend Developer & Backend Integration",
        duration: "2022",
        description: "Professional real estate platform with property search, sold listings, and comprehensive tools",
        technologies: ["Bootstrap", "EJS", "JavaScript", "CSS3", "HTML5", "Font Awesome", "Node.js", "Express.js"],
        highlights: [
            'Developed complete frontend using Bootstrap from scratch',
            'Implemented property search with sale and rental categories',
            'Created sold properties tracking page',
            'Built tools section with calculators and property listing forms',
            'Developed news section with email newsletter integration',
        ],
        borderColor: "border-slate-500",
        isLarge: false,
        liveUrl: "https://www.pentzproperties.com/",
    },
    {
        title: "To Be Real Estate Website",
        role: "Frontend Developer & Backend Integration",
        duration: "2022",
        description: "Advanced real estate platform with comprehensive property categories and interactive features",
        technologies: ["Bootstrap", "EJS", "JavaScript", "CSS3", "HTML5", "Font Awesome", "Node.js", "Express.js"],
        highlights: [
            'Developed complete frontend using Bootstrap from scratch',
            'Implemented complex multi-level navigation with sub-menus',
            'Created property category pages (Buy, Sell, Rent, Commercial, Off-Plan)',
            'Built interactive sub-menu with images and contact links',
            'Developed team section with agent grid and studio information',
            'Created responsive design with custom styling and Font Awesome icons',
        ],
        borderColor: "border-slate-500",
        isLarge: false,
        liveUrl: "https://www.toberealestate.com/",
        
    },
    {
        title: "Buildwise Estimators Website",
        role: "Frontend Developer",
        duration: "2021",
        description: "Professional construction estimating website with service listings, project portfolios, and contact forms",
        technologies: ["HTML5", "CSS3", "JavaScript", "GSAP", "Font Awesome", "Tawk.to"],
        highlights: [
            'Developed complete frontend using HTML5 and CSS3 from scratch',
            'Integrating Tawk.to live chat functionality',
            'Implemented responsive navigation with mobile hamburger menu',
            'Developed about, testimonials, and footer sections',
            'Implemented GSAP animations for smooth user experience',
            'Ensured cross-browser compatibility and mobile responsiveness',
        ],
        borderColor: "border-slate-500",
        isLarge: false,
        liveUrl: "https://buildwise-estimators.com/",
    },
]
